apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-gatau
  namespace: staging
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-gatau
  namespace: staging
spec:
  hosts:
    - "*"
  gateways:
    - gw-gatau
  http:
    - route:
        - destination:
            host: gatau-svc-stag.staging.svc.cluster.local
            port:
              number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-gatau
  namespace: staging
spec:
  host: gatau-svc-stag
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
